name: github_treasures
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  google_fonts: ^5.0.0
  get_it: ^7.3.0
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^2.0.1
  json_annotation: ^4.7.0
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  uuid: ^4.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.1
  connectivity_plus: ^4.0.2
  move_to_background: ^1.0.2
  package_info_plus: ^4.1.0
  expandable: ^5.0.1
  collection: ^1.17.2
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1
  font_awesome_flutter: ^10.6.0
  flutter_gen: ^5.3.1
  infinite_scroll_pagination: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_gen_runner: 5.3.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/github_cat.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true



flutter_gen:
  output: lib/core/resource/ # Optional (default: lib/gen/)
  line_length: 80


  # integrations:
  #   flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: GithubAssets
      package_parameter_enabled: false


